=== ddradar/consumer-ddr/public/song-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://cs.ddradar.app/song-schema.json",
  "definitions": {
    "id": {
      "type": "string",
      "pattern": "^([0-9a-z]+-)*[0-9a-z]+$"
    },
    "chart": {
      "type": "object",
      "properties": {
        "playStyle": {
          "type": "string",
          "enum": [
            "SINGLE",
            "DOUBLE",
            "COUPLE",
            "UNISON",
            "6-PANELS",
            "3-PANELS",
            "STEP BATTLE",
            "BATTLE"
          ]
        },
        "difficulty": {
          "description": "Chart difficulty type.",
          "type": "integer",
          "minimum": 0
        },
        "level": {
          "description": "Chart level. (if blinked 10, set \"10+\")",
          "type": ["number", "string"],
          "minimum": 0,
          "pattern": "^([0-9]+\\+|\\?)$",
          "default": 0,
          "examples": [3, "10+", 18, "?"]
        }
      },
      "required": ["playStyle", "difficulty", "level"],
      "additionalProperties": false
    }
  },
  "title": "Song Schema",
  "type": "object",
  "properties": {
    "$schema": { "type": "string" },
    "slug": {
      "$ref": "#/definitions/id",
      "description": "Song Id"
    },
    "series": {
      "$ref": "#/definitions/id",
      "description": "Series slug"
    },
    "name": { "type": "string" },
    "artist": { "type": "string" },
    "bpm": {
      "type": ["integer", "string"],
      "exclusiveMinimum": 0,
      "pattern": "^(\\?{3}|[0-9]+-[0-9]+)$",
      "default": "???",
      "examples": [150, "100-400", "???"]
    },
    "charts": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/chart"
      },
      "minItems": 1
    }
  },
  "required": ["slug", "series", "name", "artist", "bpm", "charts"],
  "additionalProperties": false
}

=== ddradar/consumer-ddr/content/max-jp/max-300.json
{
  "slug": "max-300",
  "series": "max-jp",
  "name": "MAX 300",
  "artist": "Î©",
  "bpm": 300,
  "charts": [
    {
      "playStyle": "SINGLE",
      "difficulty": 1,
      "level": "?"
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 2,
      "level": "?"
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 3,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 1,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 2,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 3,
      "level": "?"
    }
  ]
}

=== ddradar/consumer-ddr/content/dct/peace-dct.json
{
  "slug": "peace-dct",
  "series": "dct",
  "name": "PEACE!",
  "artist": "DREAMS COME TRUE",
  "bpm": 161,
  "charts": [
    {
      "playStyle": "SINGLE",
      "difficulty": 1,
      "level": 3
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 2,
      "level": 4.5
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 3,
      "level": 6.5
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 4,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 1,
      "level": 2.5
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 2,
      "level": 8
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 3,
      "level": "?"
    },
    {
      "playStyle": "COUPLE",
      "difficulty": 1,
      "level": 3
    },
    {
      "playStyle": "COUPLE",
      "difficulty": 2,
      "level": 4.5
    },
    {
      "playStyle": "COUPLE",
      "difficulty": 3,
      "level": 6.5
    }
  ]
}

=== ddradar/consumer-ddr/content/ext2/look-at-us.json
{
  "slug": "look-at-us",
  "series": "ext2",
  "name": "LOOK AT US (Daddy DJ Remix)",
  "artist": "SARINA PARIS",
  "bpm": 135,
  "charts": [
    { "playStyle": "SINGLE", "difficulty": 0, "level": 1 },
    { "playStyle": "SINGLE", "difficulty": 1, "level": 2 },
    { "playStyle": "SINGLE", "difficulty": 2, "level": 6 },
    { "playStyle": "SINGLE", "difficulty": 3, "level": 7 },
    { "playStyle": "DOUBLE", "difficulty": 1, "level": 2 },
    { "playStyle": "DOUBLE", "difficulty": 2, "level": 5 },
    { "playStyle": "DOUBLE", "difficulty": 3, "level": 7 }
  ]
}

=== ddradar/consumer-ddr/content/ext2/la-bamba.json
{
  "slug": "la-bamba",
  "series": "ext2",
  "name": "LA BAMBA",
  "artist": "Mexican Folk Song",
  "bpm": 179,
  "charts": [
    { "playStyle": "SINGLE", "difficulty": 0, "level": 1 },
    { "playStyle": "SINGLE", "difficulty": 1, "level": 3 },
    { "playStyle": "SINGLE", "difficulty": 2, "level": 5 },
    { "playStyle": "SINGLE", "difficulty": 3, "level": 8 },
    { "playStyle": "DOUBLE", "difficulty": 1, "level": 4 },
    { "playStyle": "DOUBLE", "difficulty": 2, "level": 5 },
    { "playStyle": "DOUBLE", "difficulty": 3, "level": 8 }
  ]
}

=== ddradar/consumer-ddr/content/3rd/brilliant-2u-orchestra-groove.json
{
  "slug": "brilliant-2u-orchestra-groove",
  "series": "3rd",
  "name": "BRILLIANT 2U (Orchestra-Groove)",
  "artist": "NAOKI",
  "bpm": 150,
  "charts": [
    {
      "playStyle": "SINGLE",
      "difficulty": 1,
      "level": 5
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 2,
      "level": 6
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 3,
      "level": 7
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 1,
      "level": 4
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 2,
      "level": 5
    },
    {
      "playStyle": "UNISON",
      "difficulty": 1,
      "level": 5
    },
    {
      "playStyle": "UNISON",
      "difficulty": 2,
      "level": 6
    },
    {
      "playStyle": "UNISON",
      "difficulty": 3,
      "level": 7
    }
  ]
}

=== ddradar/consumer-ddr/content/strike/in-my-eyes-midihead.json
{
  "slug": "in-my-eyes-midihead",
  "series": "strike",
  "name": "In My Eyes (Midihead Remix)",
  "artist": "Midihead",
  "bpm": 142,
  "charts": [
    { "playStyle": "SINGLE", "difficulty": 0, "level": 1 },
    { "playStyle": "SINGLE", "difficulty": 1, "level": 4 },
    { "playStyle": "SINGLE", "difficulty": 2, "level": 6 },
    { "playStyle": "SINGLE", "difficulty": 3, "level": 9 },
    { "playStyle": "DOUBLE", "difficulty": 1, "level": 4 },
    { "playStyle": "DOUBLE", "difficulty": 2, "level": 7 },
    { "playStyle": "DOUBLE", "difficulty": 3, "level": 9 }
  ]
}

=== ddradar/consumer-ddr/content/gb3/1-2-3-4-007-hard.json
{
  "slug": "1-2-3-4-007-hard",
  "series": "gb3",
  "name": "1,2,3,4,007 (HARD)",
  "artist": "NI-NI",
  "bpm": 140,
  "charts": [
    {
      "playStyle": "SINGLE",
      "difficulty": 1,
      "level": 4
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 2,
      "level": 6
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 3,
      "level": 8
    }
  ]
}

=== ddradar/consumer-ddr/content/max-jp/yozora-no-muko.json
{
  "slug": "yozora-no-muko",
  "series": "max-jp",
  "name": "夜空ノムコウ",
  "artist": "EUROBEAT LOVERS",
  "bpm": 156,
  "charts": [
    {
      "playStyle": "SINGLE",
      "difficulty": 1,
      "level": "?"
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 2,
      "level": "?"
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 3,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 1,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 2,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 3,
      "level": "?"
    }
  ]
}
