=== ddradar/consumer-ddr/public/song-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://cs.ddradar.app/song-schema.json",
  "definitions": {
    "id": {
      "type": "string",
      "pattern": "^([0-9a-z]+-)*[0-9a-z]+$"
    },
    "chart": {
      "type": "object",
      "properties": {
        "playStyle": {
          "type": "string",
          "enum": [
            "SINGLE",
            "DOUBLE",
            "COUPLE",
            "UNISON",
            "6-PANELS",
            "3-PANELS",
            "STEP BATTLE",
            "BATTLE"
          ]
        },
        "difficulty": {
          "description": "Chart difficulty type.",
          "type": "integer",
          "minimum": 0
        },
        "level": {
          "description": "Chart level. (if blinked 10, set \"10+\")",
          "type": ["number", "string"],
          "minimum": 0,
          "pattern": "^([0-9]+\\+|\\?)$",
          "default": 0,
          "examples": [3, "10+", 18, "?"]
        }
      },
      "required": ["playStyle", "difficulty", "level"],
      "additionalProperties": false
    }
  },
  "title": "Song Schema",
  "type": "object",
  "properties": {
    "$schema": { "type": "string" },
    "slug": {
      "$ref": "#/definitions/id",
      "description": "Song Id"
    },
    "series": {
      "$ref": "#/definitions/id",
      "description": "Series slug"
    },
    "name": { "type": "string" },
    "artist": { "type": "string" },
    "bpm": {
      "type": ["integer", "string"],
      "exclusiveMinimum": 0,
      "pattern": "^(\\?{3}|[0-9]+-[0-9]+)$",
      "default": "???",
      "examples": [150, "100-400", "???"]
    },
    "charts": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/chart"
      },
      "minItems": 1
    }
  },
  "required": ["slug", "series", "name", "artist", "bpm", "charts"],
  "additionalProperties": false
}

=== ddradar/consumer-ddr/content/tkd/pure-mind.json
{
  "slug": "pure-mind",
  "series": "tkd",
  "name": "PURE MIND",
  "artist": "TRUE KiSS DESTiNATiON",
  "bpm": 120,
  "charts": [
    {
      "playStyle": "SINGLE",
      "difficulty": 1,
      "level": 3
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 2,
      "level": 4
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 3,
      "level": 6
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 4,
      "level": "?"
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 0,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 1,
      "level": 4
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 2,
      "level": 7.5
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 3,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 0,
      "level": "?"
    },
    {
      "playStyle": "COUPLE",
      "difficulty": 1,
      "level": 3
    },
    {
      "playStyle": "COUPLE",
      "difficulty": 2,
      "level": 4
    },
    {
      "playStyle": "COUPLE",
      "difficulty": 3,
      "level": 6
    }
  ]
}

=== ddradar/consumer-ddr/content/max2-us/i-need-you.json
{
  "slug": "i-need-you",
  "series": "max2-us",
  "name": "I Need You",
  "artist": "Supa Fova feat. Jenny F.",
  "bpm": 114,
  "charts": [
    { "playStyle": "SINGLE", "difficulty": 0, "level": 1 },
    { "playStyle": "SINGLE", "difficulty": 1, "level": 3 },
    { "playStyle": "SINGLE", "difficulty": 2, "level": 4 },
    { "playStyle": "SINGLE", "difficulty": 3, "level": 5 },
    { "playStyle": "DOUBLE", "difficulty": 1, "level": 3 },
    { "playStyle": "DOUBLE", "difficulty": 2, "level": 5 },
    { "playStyle": "DOUBLE", "difficulty": 3, "level": 6 }
  ]
}

=== ddradar/consumer-ddr/content/2nd/dub-i-dub.json
{
  "slug": "dub-i-dub",
  "series": "2nd",
  "name": "DUB I DUB",
  "artist": "ME & MY",
  "bpm": 136,
  "charts": [
    { "playStyle": "SINGLE", "difficulty": 1, "level": 4 },
    { "playStyle": "SINGLE", "difficulty": 2, "level": 6 },
    { "playStyle": "SINGLE", "difficulty": 6, "level": 8 },
    { "playStyle": "DOUBLE", "difficulty": 1, "level": 5 },
    { "playStyle": "DOUBLE", "difficulty": 2, "level": 7 },
    { "playStyle": "COUPLE", "difficulty": 1, "level": 4 },
    { "playStyle": "COUPLE", "difficulty": 2, "level": 6 },
    { "playStyle": "COUPLE", "difficulty": 3, "level": 8 }
  ]
}

=== ddradar/consumer-ddr/content/konamix/dynamite-rave.json
{
  "slug": "dynamite-rave",
  "series": "konamix",
  "name": "DYNAMITE RAVE",
  "artist": "NAOKI",
  "bpm": 150,
  "charts": [
    { "playStyle": "SINGLE", "difficulty": 1, "level": 5 },
    { "playStyle": "SINGLE", "difficulty": 2, "level": 7 },
    { "playStyle": "SINGLE", "difficulty": 3, "level": 9 },
    { "playStyle": "DOUBLE", "difficulty": 1, "level": 5 },
    { "playStyle": "DOUBLE", "difficulty": 2, "level": 6 },
    { "playStyle": "DOUBLE", "difficulty": 4, "level": 8 },
    { "playStyle": "6-PANELS", "difficulty": 1, "level": 4 },
    { "playStyle": "6-PANELS", "difficulty": 2, "level": 7 },
    { "playStyle": "6-PANELS", "difficulty": 3, "level": 9 },
    { "playStyle": "BATTLE", "difficulty": 1, "level": 6 }
  ]
}

=== ddradar/consumer-ddr/content/konamix/afronova-primeval.json
{
  "slug": "afronova-primeval",
  "series": "konamix",
  "name": "AFRONOVA PRIMEVAL",
  "artist": "8 bit",
  "bpm": 200,
  "charts": [
    { "playStyle": "SINGLE", "difficulty": 1, "level": 4 },
    { "playStyle": "SINGLE", "difficulty": 2, "level": 6 },
    { "playStyle": "SINGLE", "difficulty": 3, "level": 9 },
    { "playStyle": "DOUBLE", "difficulty": 1, "level": 4 },
    { "playStyle": "DOUBLE", "difficulty": 2, "level": 6 },
    { "playStyle": "DOUBLE", "difficulty": 3, "level": 9 }
  ]
}

=== ddradar/consumer-ddr/content/strike/zero-one.json
{
  "slug": "zero-one",
  "series": "strike",
  "name": "ZERO-ONE",
  "artist": "Mr. T",
  "bpm": 160,
  "charts": [
    { "playStyle": "SINGLE", "difficulty": 0, "level": 1 },
    { "playStyle": "SINGLE", "difficulty": 1, "level": 4 },
    { "playStyle": "SINGLE", "difficulty": 2, "level": 6 },
    { "playStyle": "SINGLE", "difficulty": 3, "level": 9 },
    { "playStyle": "DOUBLE", "difficulty": 1, "level": 3 },
    { "playStyle": "DOUBLE", "difficulty": 2, "level": 6 },
    { "playStyle": "DOUBLE", "difficulty": 3, "level": 9 }
  ]
}

=== ddradar/consumer-ddr/content/max2-us/groove.json
{
  "slug": "groove",
  "series": "max2-us",
  "name": "Groove",
  "artist": "Sho-T feat. Brenda",
  "bpm": 130,
  "charts": [
    { "playStyle": "SINGLE", "difficulty": 0, "level": 1 },
    { "playStyle": "SINGLE", "difficulty": 1, "level": 4 },
    { "playStyle": "SINGLE", "difficulty": 2, "level": 6 },
    { "playStyle": "SINGLE", "difficulty": 3, "level": 8 },
    { "playStyle": "DOUBLE", "difficulty": 1, "level": 3 },
    { "playStyle": "DOUBLE", "difficulty": 2, "level": 6 },
    { "playStyle": "DOUBLE", "difficulty": 3, "level": 8 }
  ]
}

=== ddradar/consumer-ddr/content/max-jp/exotic-ethnic.json
{
  "slug": "exotic-ethnic",
  "series": "max-jp",
  "name": "exotic ethnic",
  "artist": "RevenG",
  "bpm": 190,
  "charts": [
    {
      "playStyle": "SINGLE",
      "difficulty": 1,
      "level": "?"
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 2,
      "level": "?"
    },
    {
      "playStyle": "SINGLE",
      "difficulty": 3,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 1,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 2,
      "level": "?"
    },
    {
      "playStyle": "DOUBLE",
      "difficulty": 3,
      "level": "?"
    }
  ]
}
