=== ddradar/consumer-ddr/static/software-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://cs.ddradar.app/software-schema.json",
  "definitions": {
    "id": {
      "description": "Unique Id (kebab-case)",
      "type": "string",
      "pattern": "^([a-z0-9]+)(-[a-z0-9]+)*$"
    },
    "song": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/id"
        },
        "name": {
          "type": "string"
        },
        "artist": {
          "type": "string"
        },
        "bpm": {
          "type": ["integer", "string"],
          "exclusiveMinimum": 0,
          "pattern": "^(\\?{3}|[0-9]+-[0-9]+)$",
          "default": "???",
          "examples": [150, "100-400", "???"]
        },
        "charts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/chart"
          },
          "minItems": 1
        }
      },
      "required": ["id", "name", "artist", "bpm", "charts"],
      "additionalProperties": false
    },
    "chart": {
      "type": "object",
      "properties": {
        "playStyle": {
          "type": "string",
          "enum": [
            "SINGLE",
            "DOUBLE",
            "COUPLE",
            "UNISON",
            "6-PANELS",
            "3-PANELS",
            "STEP BATTLE"
          ]
        },
        "difficulty": {
          "description": "Chart difficulty type.",
          "type": "integer",
          "minimum": 0
        },
        "level": {
          "description": "Chart level. (if blinked 10, set \"10+\")",
          "type": ["integer", "string"],
          "minimum": 0,
          "pattern": "^([0-9]+\\+)$",
          "default": 0,
          "examples": [3, "10+", 18, 0]
        }
      },
      "required": ["playStyle", "difficulty", "level"],
      "additionalProperties": false
    }
  },
  "title": "Software Schema",
  "type": "object",
  "properties": {
    "$schema": { "type": "string" },
    "id": {
      "$ref": "#/definitions/id"
    },
    "name": {
      "type": "string"
    },
    "region": {
      "type": "string",
      "enum": ["JP", "US", "EU"]
    },
    "platform": {
      "type": "string",
      "enum": ["Play Station", "Play Station 2", "Dreamcast", "GAME BOY", "Wii"]
    },
    "launched": {
      "type": "string",
      "format": "date"
    },
    "songs": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/song"
      },
      "minItems": 1
    },
    "difficultyNames": {
      "type": "object",
      "patternProperties": {
        "^[0-9]$": { "type": "string" }
      },
      "additionalProperties": false
    }
  },
  "required": ["id", "name", "region", "platform", "songs", "difficultyNames"],
  "additionalProperties": false
}

=== ddradar/consumer-ddr/series/best.json
{
  "$schema": "https://cs.ddradar.app/software-schema.json",
  "id": "best",
  "name": "Dance Dance Revolution BEST HITS",
  "platform": "Play Station",
  "region": "JP",
  "launched": "2000-12-21",
  "songs": [
    {
      "id": "after-the-game-of-love",
      "name": "AFTER THE GAME OF LOVE",
      "artist": "NPD3",
      "bpm": 105,
      "charts": [
        {
          "playStyle": "SINGLE",
          "difficulty": 5,
          "level": 1
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 1,
          "level": 1
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 2,
          "level": 4
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 3,
          "level": 5
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 1,
          "level": 2
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 2,
          "level": 4
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 3,
          "level": 6
        },
        {
          "playStyle": "UNISON",
          "difficulty": 1,
          "level": 1
        },
        {
          "playStyle": "UNISON",
          "difficulty": 2,
          "level": 4
        },
        {
          "playStyle": "UNISON",
          "difficulty": 3,
          "level": 5
        }
      ]
    },
    {
      "id": "boom-boom-dollar",
      "name": "BOOM BOOM DOLLAR",
      "artist": "King Kong & D. Jungle Girls",
      "bpm": 135,
      "charts": [
        {
          "playStyle": "SINGLE",
          "difficulty": 0,
          "level": 1
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 1,
          "level": 2
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 2,
          "level": 5
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 3,
          "level": 6
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 1,
          "level": 3
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 2,
          "level": 5
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 3,
          "level": 7
        },
        {
          "playStyle": "UNISON",
          "difficulty": 1,
          "level": 2
        },
        {
          "playStyle": "UNISON",
          "difficulty": 2,
          "level": 5
        },
        {
          "playStyle": "UNISON",
          "difficulty": 3,
          "level": 6
        }
      ]
    },
    {
      "id": "brilliant-2u",
      "name": "BRILLIANT 2U",
      "artist": "NAOKI",
      "bpm": 150,
      "charts": [
        {
          "playStyle": "SINGLE",
          "difficulty": 0,
          "level": 1
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 2,
          "level": 5
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 3,
          "level": 6
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 2,
          "level": 5
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 3,
          "level": 7
        },
        {
          "playStyle": "UNISON",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "UNISON",
          "difficulty": 2,
          "level": 5
        },
        {
          "playStyle": "UNISON",
          "difficulty": 3,
          "level": 6
        }
      ]
    },
    {
      "id": "butterfly-smiledk",
      "name": "butterfly",
      "artist": "smile. dk",
      "bpm": 135,
      "charts": [
        {
          "playStyle": "SINGLE",
          "difficulty": 0,
          "level": 1
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 1,
          "level": 3
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 2,
          "level": 4
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 3,
          "level": 5
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 2,
          "level": 5
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 3,
          "level": 6
        },
        {
          "playStyle": "UNISON",
          "difficulty": 1,
          "level": 3
        },
        {
          "playStyle": "UNISON",
          "difficulty": 2,
          "level": 4
        },
        {
          "playStyle": "UNISON",
          "difficulty": 3,
          "level": 5
        }
      ]
    },
    {
      "id": "captain-jack",
      "name": "CAPTAIN JACK (GRANDALE REMIX)",
      "artist": "CAPTAIN JACK",
      "bpm": 170,
      "charts": [
        {
          "playStyle": "SINGLE",
          "difficulty": 0,
          "level": 1
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 2,
          "level": 7
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 3,
          "level": 9
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 1,
          "level": 5
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 2,
          "level": 7
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 3,
          "level": 9
        },
        {
          "playStyle": "UNISON",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "UNISON",
          "difficulty": 2,
          "level": 7
        },
        {
          "playStyle": "UNISON",
          "difficulty": 3,
          "level": 9
        }
      ]
    },
    {
      "id": "dam-dariram",
      "name": "DAM DARIRAM",
      "artist": "JOGA",
      "bpm": 142,
      "charts": [
        {
          "playStyle": "SINGLE",
          "difficulty": 0,
          "level": 1
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 2,
          "level": 6
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 3,
          "level": 8
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 2,
          "level": 5
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 3,
          "level": 8
        },
        {
          "playStyle": "UNISON",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "UNISON",
          "difficulty": 2,
          "level": 6
        },
        {
          "playStyle": "UNISON",
          "difficulty": 3,
          "level": 8
        }
      ]
    },
    {
      "id": "drop-the-bomb",
      "name": "DROP THE BOMB",
      "artist": "Scotty D.",
      "bpm": 150,
      "charts": [
        {
          "playStyle": "SINGLE",
          "difficulty": 5,
          "level": 1
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 2,
          "level": 5
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 3,
          "level": 6
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 2,
          "level": 5
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 3,
          "level": 6
        },
        {
          "playStyle": "UNISON",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "UNISON",
          "difficulty": 2,
          "level": 5
        },
        {
          "playStyle": "UNISON",
          "difficulty": 3,
          "level": 6
        }
      ]
    },
    {
      "id": "dub-i-dub",
      "name": "DUB I DUB",
      "artist": "ME & MY",
      "bpm": 136,
      "charts": [
        {
          "playStyle": "SINGLE",
          "difficulty": 0,
          "level": 1
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 2,
          "level": 6
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 3,
          "level": 8
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 1,
          "level": 5
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 2,
          "level": 7
        },
        {
          "playStyle": "DOUBLE",
          "difficulty": 3,
          "level": 7
        },
        {
          "playStyle": "UNISON",
          "difficulty": 1,
          "level": 4
        },
        {
          "playStyle": "UNISON",
          "difficulty": 2,
          "level": 6
        },
        {
          "playStyle": "UNISON",
          "difficulty": 3,
          "level": 8
        }
      ]
    },
    {
      "id": "dynamite-rave",
      "name": "DYNAMITE RAVE",
      "artist": "NAOKI",
      "bpm": 150,
      "charts": [
        {
          "playStyle": "SINGLE",
          "difficulty": 0,
          "level": 1
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 1,
          "level": 5
        },
        {
          "playStyle": "SINGLE",
          "difficulty": 2,
          "level": 7
        },
